CREATE TABLE Orders (
  UsersName VARCHAR NOT NULL,
  Street VARCHAR NOT NULL,
  City VARCHAR NOT NULL,
  State VARCHAR NOT NULL, 
  TrackingID VARCHAR NOT NULL PRIMARY KEY,
  ID INT NOT NULL,
  FOREIGN KEY (ID) REFERENCES Users(ID)
);